### ISSUE TITLE
我想这边训练自己的语音识别模型

### ISSUE THREAD

**Issue by yspisgod** [robin1001/kws_on_android#3]
能提供个思路吗，我只是个对这个有兴趣的人
目前想的思路就是使用kalidi训练模型，然后通过您这个项目中的py脚本进行转化

**Comment by robin1001** [comment]
这个项目已经不维护了，好久了。语音识别的话，可以参考我的另一个项目 https://github.com/wenet-e2e/wenet/。

**Comment by yspisgod** [comment]
好的，我去根据wekws去做下
